name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1
    
    - name: Install package and test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-test.txt
        # Install ML frameworks (CPU-only versions for faster CI)
        pip install torch==2.0.1+cpu torchvision==0.15.2+cpu --index-url https://download.pytorch.org/whl/cpu
        pip install tensorflow-cpu==2.12.0
        pip install scikit-learn==1.2.2
        # Install importlib-resources for Python 3.8 compatibility (though we're not using 3.8 anymore)
        pip install importlib-resources
    
    - name: Run tests with coverage
      timeout-minutes: 15
      run: |
        python -m pytest -v --cov=deploywizard --cov-report=xml
    
    - name: Upload coverage to Codecov
      if: success() || failure()
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
